### ISSUE TITLE
配置文件语法错误

### ISSUE THREAD

**Issue by meiya927** [sazs34/TaskConfig#3]
![162936afb2337e9b1ccda57c867f372](https://user-images.githubusercontent.com/34301420/72674187-c90cc800-3aae-11ea-963f-5ee7351cba59.jpg)
商店版QuantumultX，按教程添加API KEY后运行weather_dark.js，提示配置文件语法错误。
请问是什么原因啊，要怎么解决？

**Comment by sazn1314** [comment]
https://www.notion.so/Quantumult-X-1d32ddc6e61c4892ad2ec5ea47f00917
你好,麻烦先看一下qx的配置教程
确认好这个task的js要放置在什么地方
非js问题
